name: elena-ultra-api-env  # overridden at install, so this is for your use with conda env
channels:
    - conda-forge
dependencies:
  - osmnx
  - flask
  - googlemaps
  - requests
  - networkx
  - flask_cors
  - python=3.6
  - anaconda
  - numpy
  - gunicorn